name: build_and_push
on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}

jobs:
  pre-build-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Assert committed ./output folder matches `make generate-dockerfiles` output
      run: |
        sudo apt-get install --yes make
        make clean
        make generate-dockerfiles
        if ! git diff --quiet output/; then
            echo 'output folder and docker-bits/resources out of sync!'
            exit 1
        fi

  build-and-push:
    strategy:
      fail-fast: false
      matrix:
        notebook:
          - rstudio
          - sas
          - jupyterlab-cpu
          - jupyterlab-pytorch
          - jupyterlab-tensorflow
          - remote-desktop
    needs: pre-build-checks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the Repo
      uses: actions/checkout@v4

    - name: Login to Dockerhub
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
    
    - name: Get the Current Date
      id: date
      run: echo date=$(date +'%Y-%m-%d--%M-%S') >> $GITHUB_OUTPUT

    - name: Free up all available disk space before building
      run: ./.github/scripts/cleanup_runner.sh
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  
    - name: Build and push Docker image
      uses: docker/build-push-action@v5.0.0
      with:
        context: ./output/${{ matrix.notebook }}/
        file: ./output/${{ matrix.notebook }}/Dockerfile
        push: true
        tags: ${{secrets.DOCKER_USER}}/${{ matrix.notebook }}
        labels: ${{ steps.date.outputs.date }}
