name: build_and_push
on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}

jobs:
  pre-build-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Assert committed ./output folder matches `make generate-dockerfiles` output
      run: |
        sudo apt-get install --yes make
        make clean
        make generate-dockerfiles
        if ! git diff --quiet output/; then
            echo 'output folder and docker-bits/resources out of sync!'
            exit 1
        fi
        
  build-and-push:
    strategy:
      fail-fast: false
      matrix:
        notebook:
          - rstudio
          - sas
          - jupyterlab-cpu
          - jupyterlab-pytorch
          - jupyterlab-tensorflow
          - remote-desktop
    needs: pre-build-checks
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: docker login
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
    
    - name: Get Current Date
      id: date
      run: echo date=$(date +'%Y-%m-%d--%M-%S') >> $GITHUB_OUTPUT

    - name: Echo disk usage before clean up
      run: ./.github/scripts/echo_usage.sh

    - name: Free up all available disk space before building
      run: ./.github/scripts/cleanup_runner.sh

    - name: Echo disk usage before build start
      run: ./.github/scripts/echo_usage.sh
      
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the Docker image
      id: build-image
      run: docker build output/${{ matrix.notebook }}/Dockerfile --tag $DOCKER_USER/${{ matrix.notebook }}:${{ steps.date.outputs.date }}

    - name: Echo disk usage after build completion
      run: ./.github/scripts/echo_usage.sh

    # Free up space from build process (containerscan action will run out of space if we don't)
    - run: ./.github/scripts/cleanup_runner.sh

    - name: Docker Push
      run: docker push $DOCKER_USER/${{ matrix.notebook }}:${{ steps.date.outputs.date }}
